# docker-compose.yml
version: "3.7"
services:
  db:
    image: postgis/postgis:13-3.0
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data
    restart: always
    container_name: postgres
  pgadmin:
    image: dpage/pgadmin4:5
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "80:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    container_name: pgadmin4
  # api:
  #   build:
  #     context: ./
  #     dockerfile: DockerFile
  #   depends_on:
  #     - db
  #   ports:
  #     - "5000:5000"
  #   restart: on-failure
  #   container_name: api

volumes:
  db-data:
  pgadmin-data:
