DROP TABLE IF EXISTS contacts CASCADE;
DROP TABLE IF EXISTS prestations CASCADE;
DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS formations CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS packages CASCADE;